#!/usr/bin/env bash

: "${npm_config_argv:=}"
: "${npm_package_name:=}"

warn() {
  echo "${1:-$(cat -)}" >&2
}

error() {
  warn "nodenv-package-rehash: $1"
}

main_package() {
  if [ -z "$npm_package_name" ] || [ -z "$npm_config_argv" ]; then
    error "can't determine target package"
    return 0 # still rehash by default
  fi

  local current_package='\["'$npm_package_name'("\]|@)'
  [[ $npm_config_argv =~ $current_package ]]
}

# This hook gets invoked when installing dependencies, too, but
# we only care about the "main" package installed specifically by the user.
# That way we only rehash once for a global install, not hundreds of times.
if ! main_package; then
  exit
fi

nodenv rehash
